# Generated by Django 4.2.30 on 2026-05-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=300)),
            ],
            options={
                "verbose_name": "Элемент справочника",
                "verbose_name_plural": "Элементы справочников",
            },
        ),
        migrations.CreateModel(
            name="RefBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Справочник",
                "verbose_name_plural": "Справочники",
            },
        ),
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                (
                    "refbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="refbooks.refbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Версия справочника",
                "verbose_name_plural": "Версии справочников",
            },
        ),
        migrations.AddConstraint(
            model_name="refbook",
            constraint=models.UniqueConstraint(
                fields=("code",), name="unique_refbook_code"
            ),
        ),
        migrations.AddField(
            model_name="element",
            name="version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="elements",
                to="refbooks.version",
            ),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                fields=("refbook", "version"), name="unique_version_per_refbook"
            ),
        ),
        migrations.AddConstraint(
            model_name="version",
            constraint=models.UniqueConstraint(
                fields=("refbook", "start_date"), name="unique_start_date_per_refbook"
            ),
        ),
        migrations.AddConstraint(
            model_name="element",
            constraint=models.UniqueConstraint(
                fields=("version", "code"), name="unique_element_code_per_version"
            ),
        ),
    ]
